version: 2

sources:
  - name: pipedrive
    schema: public
    description: "Raw Pipedrive tables loaded by docker init"
    tables:
      - name: deal_changes
      - name: stages
      - name: activity
      - name: activity_types
      - name: users
      - name: fields


